name: flutter_website
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # 轮播图
  flutter_swiper: ^1.1.6
  # 网路请求
  dio: ^3.0.9
  # 状态管理
  provider: ^4.0.4
  # 刷新加载数据
  flutter_easyrefresh: ^2.0.9
  # 企业及路由
  fluro: ^1.5.1
  # 加载html数据
  flutter_html: ^0.11.1
  # 日期格式化
  date_format: ^1.0.8
  # websocket处理
  web_socket_channel: ^1.1.0
  # 占位符和网络图片淡入
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/loading.jpg
    - assets/images/banners/police-huahua.jpeg
    - assets/images/banners/police-maomao.jpeg
    - assets/images/banners/police-paopao.jpeg
    - assets/images/banners/loading.gif


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
